String? countryDisplayName(String? country, {bool english = false}) =>
    (english ? _countryNamesEnglish : _countryNames)[country];

const _countryNamesEnglish = {
  'IR': 'Iran',
  'GB': 'United Kingdom',
  'US': 'United States',
  'DE': 'Germany',
  'NL': 'Netherlands',
  'FR': 'France',
  'CA': 'Canada',
  'SE': 'Sweden',
  'FI': 'Finland',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'JP': 'Japan',
  'SG': 'Singapore',
  'AE': 'United Arab Emirates',
  'TR': 'Türkiye',
  'IT': 'Italy',
  'ES': 'Spain',
  'PL': 'Poland',
  'RO': 'Romania',
  'IE': 'Ireland',
  'AU': 'Australia',
  'IN': 'India',
  'HK': 'Hong Kong',
  'KR': 'South Korea',
  'BR': 'Brazil',
  'UA': 'Ukraine',
  'CZ': 'Czechia',
  'NO': 'Norway',
  'DK': 'Denmark',
  'BE': 'Belgium',
  'BG': 'Bulgaria',
  'HU': 'Hungary',
  'PT': 'Portugal',
  'LT': 'Lithuania',
  'LV': 'Latvia',
  'EE': 'Estonia',
  'GR': 'Greece',
  'LU': 'Luxembourg',
};

const _countryNames = {
  'IR': 'ایران',
  'GB': 'بریتانیا',
  'US': 'آمریکا',
  'DE': 'آلمان',
  'NL': 'هلند',
  'FR': 'فرانسه',
  'CA': 'کانادا',
  'SE': 'سوئد',
  'FI': 'فنلاند',
  'CH': 'سوئیس',
  'AT': 'اتریش',
  'JP': 'ژاپن',
  'SG': 'سنگاپور',
  'AE': 'امارات',
  'TR': 'ترکیه',
  'IT': 'ایتالیا',
  'ES': 'اسپانیا',
  'PL': 'لهستان',
  'RO': 'رومانی',
  'IE': 'ایرلند',
  'AU': 'استرالیا',
  'IN': 'هند',
  'HK': 'هنگ‌کنگ',
  'KR': 'کره جنوبی',
  'BR': 'برزیل',
  'UA': 'اوکراین',
  'CZ': 'چک',
  'NO': 'نروژ',
  'DK': 'دانمارک',
  'BE': 'بلژیک',
  'BG': 'بلغارستان',
  'HU': 'مجارستان',
  'PT': 'پرتغال',
  'LT': 'لیتوانی',
  'LV': 'لتونی',
  'EE': 'استونی',
  'GR': 'یونان',
  'LU': 'لوکزامبورگ',
};
